### ISSUE TITLE
Make use of Laravel 5.4 toMail() Notification method for EmailVerification

### ISSUE THREAD

**Issue by djallits** [lubusIN/laravel-email-verification-app-boilerplate#9]
Reduces the footprint and complexity of the codebase. 
Maintains brand/identity with other emails generated through the system.

**Comment by introwit** [comment]
@djallits any results that prove that it increases the complexity? Also, it ain't a notification but what the Mailer is given for. Much easier to read the flow in this case. Would appreciate more defined cases from you

**Comment by djallits** [comment]
It is in keeping with the Password Resets workflow, as shown in [framework/src/Illuminate/Auth/Notifications/ResetPassword.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Notifications/ResetPassword.php)

**Comment by introwit** [comment]
@djallits I can see Laravel itself is using that but I can't buy your argument simply on that basis. If it actually is more complex for the codebase I would like to see how it is!
